#pragma once
typedef enum EventType
{
    EVENTTYPE_EMPTY = 0,

    // Public events
    EVENTTYPE_POWERON = 1,
    EVENTTYPE_POWEROFF = 2,
    EVENTTYPE_ALLY = 3,
    EVENTTYPE_MEGAMISSION = 4,
    EVENTTYPE_MEGAMISSION_F = 5,
    EVENTTYPE_IDLE = 6,
    EVENTTYPE_SCATTER = 7,
    EVENTTYPE_DESTRUCT = 8,
    EVENTTYPE_DEPLOY = 9,
    EVENTTYPE_DETONATE = 10, // New in YR
    EVENTTYPE_PLACE = 11,
    EVENTTYPE_OPTIONS = 12,
    EVENTTYPE_GAMESPEED = 13,
    EVENTTYPE_PRODUCE = 14,
    EVENTTYPE_SUSPEND = 15,
    EVENTTYPE_ABANDON = 16,
    EVENTTYPE_PRIMARY = 17,
    EVENTTYPE_SPECIAL_PLACE = 18,
    EVENTTYPE_EXIT = 19,
    EVENTTYPE_ANIMATION = 20,
    EVENTTYPE_REPAIR = 21,
    EVENTTYPE_SELL = 22,
    EVENTTYPE_SELLCELL = 23,
    EVENTTYPE_SPECIAL = 24,

    // Private events
    EVENTTYPE_FRAMESYNC = 25,
    EVENTTYPE_MESSAGE = 26,
    EVENTTYPE_RESPONSE_TIME = 27,
    EVENTTYPE_FRAMEINFO = 28,
    EVENTTYPE_SAVEGAME = 29,
    EVENTTYPE_ARCHIVE = 30,
    EVENTTYPE_ADDPLAYER = 31,
    EVENTTYPE_TIMING = 32,
    EVENTTYPE_PROCESS_TIME = 33,
    EVENTTYPE_PAGEUSER = 34,
    EVENTTYPE_REMOVEPLAYER = 35,
    EVENTTYPE_LATENCYFUDGE = 36,

    // New in YR
    EVENTTYPE_MEGAFRAMEINFO = 37,
    EVENTTYPE_PACKETTIMING = 38,
    EVENTTYPE_ABOUTTOEXIT = 39,
    EVENTTYPE_FALLBACKHOST = 40,
    EVENTTYPE_ADDRESSCHANGE = 41,
    EVENTTYPE_PLANCONNECT = 42,
    EVENTTYPE_PLANCOMMIT = 43,
    EVENTTYPE_PLANNODEDELETE = 44,
    EVENTTYPE_ALLCHEER = 45,
    EVENTTYPE_ABANDON_ALL = 46,

    // Custom
    EVENTTYPE_RESPONSE_TIME2 = 47,

    EVENTTYPE_LAST_EVENT,
} EventType;
